### ISSUE TITLE
Furoma Rift and Fort Rox Attraction Rates

### ISSUE THREAD

**Issue by francas** [olf/mhmapsolver#12]
Why are all the ARs for Furoma Rift and Fort Rox at 0.01%?

**Comment by olf** [comment]
Unfortunately, I'm not aware of any up-to-date attraction rate data for the latest areas. 

The HornTracker and the MouseHunt Calculator, which provided that data for the attraction rates, haven't been updated for a long time.

So I just added the mice with dummy attraction rates of 0.01%, but you will still be able to identify in which areas you can catch them, and in which phases in these areas, etc.

Maybe I'll remove the attraction data completely, as it's probably not very accurate any more also for other mice.

**Comment by olf** [comment]
I found a (semi-automated) way to get some AR-data for the new mice from HornTracker. This need to transform that and update the data file for the Solver.

**Comment by francas** [comment]
Looking forward to that!

**Comment by olf** [comment]
I've updated the attraction rates with much more recent data from HornTracker (in 954ae71a). However, that data does not support e.g. night phases in Fort Rox.
