### ISSUE TITLE
losing the phases/areas for labyrinth/zokor :(

### ISSUE THREAD

**Issue by Loulou6** [olf/mhmapsolver#14]
This was the most helpful information for the map solving, especially when with several hunters - the charm info is good, but knowing what 'run' we should go on to capture the map mice is much much more useful

I hope you can understand what I mean, unfortunately I have no knowledge on how to either change it back or fix anything with codes etc.  Good luck !!!

Louise

**Comment by olf** [comment]
The data I'm retrieving from horntracker doesn't have that information, but I'll check and see how I can add it again. However, the attraction rates won't be accurate for the different phases but only for the area in general. But for map solving maps, the phase information is quite handy, I agree.

**Comment by Loulou6** [comment]
if you can, that'd be great, i've forever got this map solver and mouse finder open in a tab !  good luck

**Comment by olf** [comment]
I think I'll switch back to the old data during the weekend and in parallel keep working on the new system.

**Comment by Loulou6** [comment]
Yeay :)  that's brilliant, thanks ever so much for trying to make it better though :)

**Comment by olf** [comment]
Resolved with Tsitu's dataset.
