### ISSUE TITLE
Zones in FW and in Iceberg missing too

### ISSUE THREAD

**Issue by JoeGrizzly** [olf/mhmapsolver#15]
Snowblind	
Iceberg 2.06%
Iceberg
SUPER|brie+ 1.81%

Crimson Ranger	
Fiery Warpath
SUPER|brie+
Super Warpath Archer
the zones at which these mice appear is greatly needed

**Comment by olf** [comment]
Ok, thanks, I'll look into options how to merge the new attraction rates with the phase data.

**Comment by olf** [comment]
I'll switch back to the old data during the weekend and in parallel keep working on the new system.

**Comment by olf** [comment]
Resolved with Tsitu's dataset.
