### ISSUE TITLE
Nibbler is now an unknown mouse on finder

### ISSUE THREAD

**Issue by JoeGrizzly** [olf/mhmapsolver#17]
Unknown

Nibbler

**Comment by olf** [comment]
I'm experiencing issues with Horntracker when trying to get the latest data for Nibbler. 😞

**Comment by JoeGrizzly** [comment]
ok wasnt sure if you knew lol

**Comment by olf** [comment]
I'll switch back to the old data during the weekend and in parallel keep working on the new system.

**Comment by olf** [comment]
Resolved with Tsitu's dataset.
