### ISSUE TITLE
Cook Mouse

### ISSUE THREAD

**Issue by JoeGrizzly** [olf/mhmapsolver#18]
Cook	
S.S. Huntington III
Dumpling Cheese
S.S. Huntington III
Dumpling Cheese
Firecracker

**Comment by olf** [comment]
Sorry, no, it's not in the dataset yet. mhmapsolver uses the dataset of [Tsitu's tools](https://github.com/tsitu/MH-Tools). Currently, I don't have an easy way to include additional mice in my dataset.
