### ISSUE TITLE
displaying  mice that are not even on my map

### ISSUE THREAD

**Issue by JoeGrizzly** [olf/mhmapsolver#19]
I need 2 Tech mice and its telling me where myst tower mice are and other tech mice I dont need in the list that goes downward right next to where the list is

**Comment by olf** [comment]
Which mice do you need? And which are listed in your map? Are you using the bookmarklet?

I'm afraid I'd need a couple more details.

**Comment by JoeGrizzly** [comment]
just tech pawn and tech Queen
but was listing all tower mice basically i wish there was a way to choose which view you want i dont personally like the one that scrolls downward on the screen next to the list i would just prefer to see the lower section alone

**Comment by olf** [comment]
Just to be sure: did you notice the "Mice Overview" Link at the top of the list on the right? That one takes you directly to the lower list, without scrolling.

**Comment by JoeGrizzly** [comment]
ok TY

**Comment by olf** [comment]
Closing.
