### ISSUE TITLE
Dashing Buccaneer?

### ISSUE THREAD

**Issue by MIbookl0ver** [olf/mhmapsolver#22]
wondering if the pirate mice were added to the mhmapsolver - didn't have the dashing buccaneer.

**Comment by olf** [comment]
Sorry, no, it's not in the dataset yet. mhmapsolver uses the dataset of [Tsitu's tools](https://github.com/tsitu/MH-Tools). Currently, I don't have an easy way to include additional mice in my dataset.

**Comment by MIbookl0ver** [comment]
Well, you have an awesome mapsolver site.  I've been using it for years and
love it.  I'll just have to find another for the newer mice, but yours will
be my favorite for the classic mice.  :)  Thanks for putting the work into
creating it.
